export enum FormFieldType {
    INPUT = "INPUT",
    TEXTAREA = "TEXTAREA",
    CHECKBOX = "CHECKBOX",
    SELECT = "SELECT",
    DATE_PICKER = "DATE_PICKER",
    COLOR_PICKER = 'COLOR',
    RADIO = "RADIO",
    COMBOBOX = "COMBOBOX",
    QUANTITY_CONTROLLER = "QUANTITY_CONTROLLER",
    CHECKBOX_GROUP = "CHECKBOX_GROUP",
}